spring:
  datasource:
      url: jdbc:mysql://localhost:3306/question_answer?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
